package me.chrr.tapestry.config.annotation;

import org.jspecify.annotations.NullMarked;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Define the prefix appended to all translation keys generated by the config reflector. This is combined with both
/// {@link SerializeName} and {@link SerializeName.Strategy} to result in the final translation key as follows:
///
/// - Default screen title: `[prefix].title`
/// - {@link Title}-annotated screen title: `[prefix].[title-name].title`
/// - Option name: `[prefix].option.[option-name]`
/// - Enum value: `[prefix].option.[option-name].[value-name]`
/// - Header name: `[prefix].category.[header-name]`
///
/// When in doubt, you can temporarily remove the annotation, which will show the second part of the translation key.
@NullMarked
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface TranslationPrefix {
    String value();
}
